springbootplus:
  isEnableAnsi: false
  login:
    token:
      valid:
        time:
          minute: 30

server:
  port: 8888
  servlet:
    context-path: /api
spring:
  datasource:
    password: ''
    url: ''
    username: ''
  redis:
    database: 0
    host: ''
    password: ''
    port: 6379
