# spring-boot-plus Common Config

############################# 访问路径、端口tomcat start #############################
server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
############################# 访问路径、端口tomcat end ###############################


################################ spring config start ###############################
spring:
  application:
    name: spring-boot-plus
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  banner:
    charset: UTF-8
    location: classpath:config/banner.txt

# 当前项目maven激活环境，例如：local/dev/test，对应pom.xml中profile设置值
---
spring:
  profiles:
    active: '@profileActive@'

# logback.xml中有详细的日志配置
logging:
  config: classpath:config/logback.xml
  #  方便Spring Boot Admin页面上实时查看日志
  file:
    name: logs/spring-boot-plus.log
################################ spring config end #################################


############################## spring-boot-plus start ##############################
spring-boot-plus:
  # 是否启用ansi控制台输出有颜色的字体
  enable-ansi: true
  # 是否启用验证码
  enable-verify-code: false
  # 过滤器配置
  filter:
    # 请求路径Filter配置
    request-path:
      enabled: true
      include-paths: /**
      # 排除路径，多行字符串配置
      exclude-paths: |
        /applications/**,/actuator/**,/instances/**,/logfile,/sba-settings.js,/assets/img/favicon.png,
        /swagger-ui.html,/swagger-resources/**,/webjars/springfox-swagger-ui/**,/v2/api-docs,
        /druid/**,/favicon.ico
  # 拦截器配置
  interceptor:
    permission:
      enabled: false
      include-paths: /**
      exclude-paths: /swagger-resources/**,/api-docs/**,/v2/api-docs/**,/adminLogin,/sysLogin,/login.html,/verificationCode,/doc/**,/error/**,/docs,/resource/**
    resource:
      enabled: true
      include-paths: ${spring-boot-plus.resource-access-patterns}
    upload:
      enabled: true
      include-paths: /upload/**
    download:
      enabled: true
      include-paths: /download/**

  # AOP配置
  aop:
    log:
      # 是否启用
      enabled: true
      # 1.请求和响应分开，按照执行顺序打印
      # 2.ThreadLocal线程绑定，方法执行结束时，连续打印请求和响应日志
      # 3.ThreadLocal线程绑定，方法执行结束时，同时打印请求和响应日志
      print-type: 1
      # 请求日志在控制台是否格式化输出，local环境建议开启，服务器环境设置为false
      request-log-format: true
      # 响应日志在控制台是否格式化输出，local环境建议开启，服务器环境设置为false
      response-log-format: true

  # 文件上传下载配置
  # 上传路径配置
  upload-path: /opt/upload/
  # 资源访问路径
  resource-access-path: /resource/
  # 资源访问路径匹配：/resource/**
  resource-access-patterns: ${spring-boot-plus.resource-access-path}**
  # 资源访问全路径前缀：http://localhost:8888/resource/
  resource-access-url: http://localhost:${server.port}${server.servlet.context-path}${spring-boot-plus.resource-access-path}
  # 全局允许上传的类型
  allow-upload-file-extensions: jpg,png,docx,xlsx,pptx,pdf
  allow-download-file-extensions: jpg,png,docx,xlsx,pptx,pdf

  ############################ CORS start ############################
  # CORS跨域配置，默认允许跨域
  cors:
    # 是否启用跨域，默认启用
    enable: true
    # CORS过滤的路径，默认：/**
    path: /**
    # 允许访问的源
    allowed-origins: '*'
    # 允许访问的请求头
    allowed-headers: x-requested-with,content-type,token
    # 是否允许发送cookie
    allow-credentials: true
    # 允许访问的请求方式
    allowed-methods: OPTION,GET,POST
    # 允许响应的头
    exposed-headers: token
    # 该响应的有效时间默认为30分钟，在有效时间内，浏览器无须为同一请求再次发起预检请求
    max-age: 1800

  ############################ CORS end ##############################

  ########################## Resource start ##########################
  # 静态资源访问配置
  resource-handlers: |
    /static/**=classpath:/static/
    /templates/**=classpath:/templates/
    swagger-ui.html=classpath:/META-INF/resources/
    /webjars/**=classpath:/META-INF/resources/webjars/
  ########################## Resource end ############################

  ######################## Spring Shiro start ########################
  shiro:
    # 是否启用
    enable: true
    # shiro ini 多行字符串配置
    filter-chain-definitions: |
      /=anon
      /static/**=anon
      /templates/**=anon
      /druid/**=anon
      /hello/world=anon
      /ip/**=anon
      /sysLog/**=anon
      /verificationCode/**=anon
      /resource/**=anon
    # 权限配置
    permission:
        # 排除登陆登出相关
      - urls: /login,/logout
        permission: anon
        # 排除静态资源
      - urls: /static/**,/templates/**
        permission: anon
        # 排除Swagger
      - urls: /docs,/swagger-ui.html,/webjars/springfox-swagger-ui/**,/swagger-resources/**,/v2/api-docs
        permission: anon
        # 排除SpringBootAdmin
      - urls: /,/favicon.ico,/actuator/**,/instances/**,/assets/**,/sba-settings.js,/applications/**
        permission: anon
        # 测试
      - url: /sysUser/getPageList
        permission: anon
  ######################## Spring Shiro end ##########################

  ############################ JWT start #############################
  jwt:
    # token请求头名称
    token-name: token
    # jwt密钥
    secret: 666666
    # 发行人
    issuer: spring-boot-plus
    # 观众
    audience: web
    # 默认过期时间1小时，单位：秒
    expire-second: 3600
    # 是否刷新token
    refresh-token: true
    # 刷新token的时间间隔，默认10分钟，单位：秒
    refresh-token-countdown: 600
    # redis校验jwt token是否存在,可选
    redis-check: true
    # true: 同一个账号只能是最后一次登陆token有效，false：同一个账号可多次登陆
    single-login: false
    # 盐值校验，如果不加自定义盐值，则使用secret校验
    salt-check: true
  ############################ JWT end ###############################

############################### spring-boot-plus end ###############################


############################### mybatis-plus start #################################
mybatis-plus:
  # 启动时是否检查MyBatis XML文件是否存在
  check-config-location: true
  # MyBatis原生配置
  configuration:
    # 字段名称下划线转驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: id_worker
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  # mapper xml映射路径
  mapper-locations: classpath*:mapper/**/*Mapper.xml
################################ mybatis-plus end ##################################


############################### DRUID数据源配置 start ################################
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filter:
        slf4j:
          enabled: true
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 3000
        wall:
          config:
            delete-allow: true
            drop-table-allow: false
          enabled: true
      filters: stat,wall,slf4j
      initial-size: 10
      max-active: 100
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 10
      pool-prepared-statements: true
      stat-view-servlet:
        enabled: true
        login-password: druid123
        login-username: druid
        url-pattern: /druid/*
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
      validation-query-timeout: 60000
    type: com.alibaba.druid.pool.DruidDataSource
############################### DRUID数据源配置 end ################################


############################### Redis 公共配置 start ###############################
---
spring:
  redis:
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-idle: 8
        max-wait: 10s
        min-idle: 2
      shutdown-timeout: 3s
############################### Redis 公共配置 end ##################################


#################################### Swagger start #################################
# swagger配置
swagger:
  base:
    package: io.geekidea.springbootplus
  contact:
    email: geekidea@qq.com
    name: geekidea
    url: ''
  description: ''
  title: spring-boot-plus
  url: ''
  version: 1.0
#################################### Swagger end ###################################


############################## Spring boot admin start ##############################
---
spring:
  boot:
    admin:
      client:
        url: http://localhost:${server.port}/${server.servlet.context-path}

# 开启和暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      enabled: true         #可在线查看日志

# 自定义项目信息，Spring Boot Admin展示使用
info:
  project-groupId: '@project.groupId@'
  project-artifactId: '@project.artifactId@'
  project-name: '@project.name@'
  project-finalName: '@project.build.finalName@'
  project-author: ${swagger.contact.name}
  project-description: '@project.description@'
  project-sourceEncoding: '@project.build.sourceEncoding@'
  project-spring-boot-version: '@spring-boot.version@'
  project-mybatis-plus-version: '@mybatis-plus-boot-starter.version@'
  project-version: '@project.version@'
############################## Spring boot admin end ###############################

