spring-boot-plus:
  # 是否启用ansi控制台输出有颜色的字体，local环境建议开启，服务器环境设置为false
  enable-ansi: false

  # AOP配置
  aop:
    log:
      # 是否启用
      enabled: true
      # 1.请求和响应分开，按照执行顺序打印
      # 2.ThreadLocal线程绑定，方法执行结束时，连续打印请求和响应日志
      # 3.ThreadLocal线程绑定，方法执行结束时，同时打印请求和响应日志
      print-type: 1
      # 请求日志在控制台是否格式化输出，local环境建议开启，服务器环境设置为false
      request-log-format: false
      # 响应日志在控制台是否格式化输出，local环境建议开启，服务器环境设置为false
      response-log-format: false

spring:
  datasource:
    url:
    username:
    password:

  # Redis配置
  redis:
    database:
    host:
    password:
    port:

